---

- set_fact:
    proxy_conf: "{{proxy_env if proxy_env is defined else '{\"http_proxy\": \"\", \"https_proxy\": \"\"}'}}"

- name: Fetch kubernetes dashboard resource
  uri:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
    return_content: yes
  register: dashboard_rs
  environment: "{{proxy_conf}}"

- name: Deploy kubernetes dashboard into cluster
  when: init_cluster and started_kubelet and enable_dashboard
  command: |
    kubectl --kubeconfig={{ kubeadmin_config }} \
        apply -f -
  args:
    stdin: "{{dashboard_rs.content}}"
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  ignore_errors: True
