---

pinned_hosts: ['provisioner', 'kubernetes']
default_lease_time: 600
max_lease_time: 7200
log_facility: local7
subnets: ['10.100.0.0', '10.100.1.0']
next_server: "{{ provisioner }}"
#domain_name_servers: "{{ provisioner }},1.1.1.1"
domain_name_servers: "1.1.1.1,1.0.0.1"
netmask: "{{ node_mask }}"
